import type { Metadata } from "next"
import { Layout, Navbar } from "nextra-theme-docs"
import { getPageMap } from "nextra/page-map"
import "./globals.css"
import "nextra-theme-docs/style.css"

export const metadata: Metadata = {
  title: {
    default: "Zenithui",
    template: "%s - Zenithui",
  },
  description: "Generated by create next app",
  applicationName: "Zenithui-Docs",
  generator: "Next.js",
  appleWebApp: {
    title: "Zenithui-Docs",
  },
}

const navbar = (
  <Navbar
    logo={
      <div>
        <b>Zenithui</b>
      </div>
    }
    projectLink="https://github.com/ChanduBobbili/ZenithUi"
  />
)

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const pageMap = await getPageMap()
  return (
    <html lang="en">
      <body className="antialiased">
        <Layout
          navbar={navbar}
          footer={<></>}
          editLink={null}
          docsRepositoryBase="https://github.com/ChanduBobbili/ZenithUi"
          sidebar={{ defaultMenuCollapseLevel: 1 }}
          pageMap={pageMap}
          navigation={{
            prev: true,
            next: true,
          }}
          darkMode={true}
          themeSwitch={{
            dark: "Dark",
            light: "Light",
            system: "System",
          }}
        >
          {children}
        </Layout>
      </body>
    </html>
  )
}
