name: Publish Package to NPM

on:
  push:
    tags:
      - "*" # Trigger on any tag

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Ensures full Git history
          ref: main # Ensure you check out a named branch

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*" # Use the latest LTS version of Node.js
          registry-url: "https://registry.npmjs.org/"

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Extract package and version from tag
        id: extract
        run: |
          TAG_NAME=${{ github.ref_name }}
          PACKAGE_NAME=$(echo "$TAG_NAME" | cut -d'@' -f1)
          PACKAGE_VERSION=$(echo "$TAG_NAME" | cut -d'@' -f2)
          echo "PACKAGE_NAME=$PACKAGE_NAME" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV
          echo "PACKAGE_NAME=$PACKAGE_NAME"
          echo "PACKAGE_VERSION=$PACKAGE_VERSION"

      - name: Skip publishing for zenithui-docs
        if: env.PACKAGE_NAME == 'zenithui-docs'
        run: echo "Skipping publish for zenithui-docs"

      - name: Navigate to package directory and install dependencies
        if: env.PACKAGE_NAME != 'zenithui-docs'
        run: |
          cd packages/$PACKAGE_NAME
          pnpm install

      - name: Lint package
        if: env.PACKAGE_NAME != 'zenithui-docs'
        run: |
          cd packages/$PACKAGE_NAME
          pnpm lint

      - name: Build package
        if: env.PACKAGE_NAME != 'zenithui-docs'
        run: |
          cd packages/$PACKAGE_NAME
          pnpm build

      - name: Publish package
        if: env.PACKAGE_NAME != 'zenithui-docs'
        run: |
          cd packages/$PACKAGE_NAME
          npm publish --access public --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Clear build artifacts
        run: rm -rf dist

      - name: Remove node_modules
        run: rm -rf node_modules
